### PR TITLE
Vulnerability fixes

### PR DESCRIPTION
**Pull request by abrahamspaa**
Bump package versions to address the below,

https://github.com/advisories/GHSA-35jh-r3h4-6jhm
https://github.com/advisories/GHSA-fvqr-27wr-82fm

### CODE REVIEW

**Comment by abrahamspaa** [comment]
Hello @WooDzu / @alanclarke / @doublerebel, Can you please check on this PR?

**Comment by alanclarke** [comment]
Thanks for this @abrahamspaa !

**Review by alanclarke — APPROVED** [review]

**Comment by paulashwin** [comment]
Thank you @alanclarke for merging this, can we release it?

**Comment by musaffa** [comment]
Screenshot from 2021-06-10 04-21-37

Experiencing this error. Shouldn't it be `lodash/defaultsDeep` instead of `lodash/defaultsdeep`?

**Comment by alanclarke** [comment]
Thanks @musaffa, just pushed a fix

**Comment by abrahamspaa** [comment]
Sorry for the miss. Thank you @musaffa.

**Pull request merged**
