### PR TITLE
Making parse more robust

### PR DESCRIPTION
**Pull request by rek**
This was failing when the content of JSON responses was not JSON.

### CODE REVIEW

**Comment by doublerebel** [comment]
Hi @rek, thanks for your contribution.

The behavior of jQuery ([doc here under dataType](http://api.jquery.com/jquery.ajax/#jQuery-ajax-settings)) is to reject malformed JSON and throw a parse error.  Changing this behavior might break existing apps using najax.  Would it be possible for you to use najax with a plain `text` dataType and parse JSON in your own code?

**Comment by rek** [comment]
Ahh ok, interesting. I'll give that shot :) Thanks.

**Comment by JoshuaCWebDeveloper** [comment]
@rek was on the right track here. jQuery actually doesn't allow the parse error to bubble up, and only returns it to the success handler. #46 Attempts to emulate that behavior.

**Comment by alanclarke** [comment]
@rek @JoshuaCWebDeveloper is this superseded by #56?

**Comment by rek** [comment]
Ahh I have no idea, was a while ago. I am happy to close this PR now though, it's a touch old.

**Pull request closed without merging**
